# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "VM was started"

  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/bionic64"
    web.vm.network 'forwarded_port', guest: 80, host: 9090

#     web.vm.provider "virtualbox" do |vb|
#       vb.gui = false
#       vb.memory = "1024"
#       d.image = "gb-demo-app"
#       d.ports = ["9090:3001"]
#       d.name = "gb-demo-vm-app"
#     end

    config.vm.provider "docker" do |d|
      d.image = "gb-demo-app"
      d.ports = ["9090:3001"]
      d.name = "gb-demo-vm-app"
    end
  end
end
