# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant.configure("2") do |config|
#   config.vm.provision "shell", inline: "VM was started"
#
#   config.vm.define "web" do |web|
#     web.vm.box = "hashicorp/bionic64"
#     web.vm.network 'forwarded_port', guest: 6379, host: 6379
#
#     web.vm.provider "virtualbox" do |vb|
#       vb.gui = false
#       vb.memory = "1024"
#     end
#   end
#   # SHELL
# end

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "redis:latest"
    d.ports = ["6379:6379"]
    d.name = "gb-demo-redis"
  end
end
